server:
  port: 8700
#springboot-web已经去掉 不用配置web相关参数
############################################################
#
# 配置项目信息
#
############################################################
spring:
  application:
    name: service-gateway
  cloud:
#    zookeeper:
#      connect-string: 192.168.170.133:2181
    nacos:
      discovery:
        server-addr: 192.168.170.133:8848   # nacos 所在地址
    gateway:
      discovery:
        locator:
#          enabled: true       # 开启动态路由，从注册中心根据微服务名称获得目标节点
      routes:
        - id: service-teacher-Route    # 路由id，可以自定义，保证全局唯一
          uri: lb://service-teacher        # lb 代表负载均衡，会动态寻址
#          uri: http://192.168.1.82:8001    # 后端微服务节点的路由uri地址
          predicates:         # 匹配断言，符合条件的则放行（可以精确到具体的接口名）
            - Path=/service-teacher/teacher/**
# 打开监控
management:
  endpoints:
    web:
      exposure:
        include: '*'