server:
  port: ${port:8002}
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可
  servlet:
    context-path: /service-student
############################################################
#
# 配置项目信息
#
############################################################
spring:
  application:
    name: service-student
  cloud:
#    zookeeper:
#      connect-string: 192.168.170.133:2181
    nacos:
      discovery:
        server-addr: 192.168.170.133:8848   # nacos 所在地址
# 打开监控
management:
  endpoints:
    web:
      exposure:
        include: '*'